"""Deployment artefact templates.

The Deploy tab writes these out filled in with the port, paths and image name the
user actually chose, so "deploy" is a button rather than a documentation
exercise. The same templates generate the committed ``deploy/`` directory.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

DOCKERFILE = """# ARCHIVIST — apparel design pipeline (Gradio)
FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    GRADIO_SERVER_NAME=0.0.0.0 \\
    GRADIO_SERVER_PORT={port}

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
        libjpeg62-turbo zlib1g libwebp7 libopenjp2-7 curl \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY archivist ./archivist
COPY README.md ./

# Runs and the style lock live on a volume so a redeploy never loses a collection.
VOLUME ["/app/runs"]
EXPOSE {port}

HEALTHCHECK --interval=30s --timeout=5s --start-period=40s \\
  CMD curl -fsS http://localhost:{port}/ >/dev/null || exit 1

CMD ["python", "-m", "archivist.app", "--host", "0.0.0.0", "--port", "{port}"]
"""

COMPOSE = """services:
  archivist:
    build: ..
    image: {image}
    container_name: archivist
    restart: unless-stopped
    ports:
      - "{port}:{port}"
    environment:
      # Keys come from the host environment or a .env file next to this compose file.
      BFL_API_KEY: ${{BFL_API_KEY:-}}
      PEXELS_API_KEY: ${{PEXELS_API_KEY:-}}
      OPENAI_API_KEY: ${{OPENAI_API_KEY:-}}
      REDDIT_CLIENT_ID: ${{REDDIT_CLIENT_ID:-}}
      REDDIT_CLIENT_SECRET: ${{REDDIT_CLIENT_SECRET:-}}
      X_BEARER_TOKEN: ${{X_BEARER_TOKEN:-}}
      META_ACCESS_TOKEN: ${{META_ACCESS_TOKEN:-}}
      META_IG_USER_ID: ${{META_IG_USER_ID:-}}
      ARCHIVIST_RUNS_DIR: /app/runs
      ARCHIVIST_COLLECTION: ${{ARCHIVIST_COLLECTION:-default}}
    volumes:
      - archivist-runs:/app/runs

volumes:
  archivist-runs:
"""

SYSTEMD = """[Unit]
Description=ARCHIVIST apparel design pipeline (Gradio)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={user}
WorkingDirectory={workdir}
EnvironmentFile=-{workdir}/.env
ExecStart={workdir}/.venv/bin/python -m archivist.app --host 0.0.0.0 --port {port}
Restart=on-failure
RestartSec=5
# The scheduler keeps running between requests, so give it a clean stop.
KillSignal=SIGINT
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
"""

WINDOWS_TASK = """<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Start ARCHIVIST (Gradio) at logon</Description>
    <URI>\\ARCHIVIST</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <StartWhenAvailable>true</StartWhenAvailable>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{workdir}\\run_archivist.bat</Command>
      <Arguments>--port {port}</Arguments>
      <WorkingDirectory>{workdir}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
"""

HF_SPACE_README = """---
title: Archivist
emoji: 🗄️
colorFrom: gray
colorTo: indigo
sdk: gradio
sdk_version: {gradio_version}
app_file: space_app.py
pinned: false
---

# ARCHIVIST

Trend research → reference mining → BFL Context → apparel graphics.

Set `BFL_API_KEY` (and optionally `PEXELS_API_KEY`, `OPENAI_API_KEY`, plus the
Reddit/X/Meta discovery credentials) as Space secrets. Without them the Space still runs in offline mode with synthetic
references, which is enough to see the whole pipeline work.

Note: Space storage is ephemeral unless persistent storage is enabled — attach a
disk and point `ARCHIVIST_RUNS_DIR` at it if you want the collection style lock
and run history to survive a restart.
"""

HF_SPACE_APP = '''"""Hugging Face Space entry point."""

import os

from archivist.app import build_app

os.environ.setdefault("ARCHIVIST_RUNS_DIR", os.environ.get("ARCHIVIST_RUNS_DIR", "runs"))

demo = build_app()

if __name__ == "__main__":
    demo.queue().launch(server_name="0.0.0.0", server_port=int(os.environ.get("PORT", 7860)))
'''

NOTES = """# Deployment notes

Generated by the ARCHIVIST Deploy tab.

## Docker

    docker compose -f docker-compose.yml up -d --build
    # open http://localhost:{port}

Runs and the collection style lock live in the `archivist-runs` volume.

## systemd (Ubuntu 24.04)

    sudo cp archivist.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable --now archivist
    journalctl -u archivist -f

## Windows (start at logon)

    schtasks /Create /TN ARCHIVIST /XML windows-task.xml

## Hugging Face Space

Copy `space_app.py`, `README.md`, `requirements.txt` and the `archivist/` package
into a new Gradio Space, then add your API keys as Space secrets.

## Exposing it

`--share` gives a temporary public Gradio URL — convenient, but it forwards to
your machine, so only use it for a demo. For anything permanent put the app
behind a reverse proxy with TLS and basic auth, or run
`python -m archivist.app --auth user:password`.
"""


def materialise(
    target_dir: Path | str,
    *,
    port: int = 7860,
    image: str = "archivist:latest",
    user: str = "ubuntu",
    workdir: str = "/opt/archivist",
    windows_workdir: str = r"C:\\archivist",
    gradio_version: str = "",
) -> list[str]:
    """Write every deployment artefact and return the paths written."""
    if not gradio_version:
        try:  # the Space needs the sdk_version it will actually run
            import gradio  # type: ignore

            gradio_version = str(gradio.__version__)
        except Exception:
            gradio_version = "5.0.0"
    target = Path(target_dir)
    target.mkdir(parents=True, exist_ok=True)
    files: dict[str, str] = {
        "Dockerfile": DOCKERFILE.format(port=port),
        "docker-compose.yml": COMPOSE.format(port=port, image=image),
        "archivist.service": SYSTEMD.format(user=user, workdir=workdir, port=port),
        "windows-task.xml": WINDOWS_TASK.format(workdir=windows_workdir, port=port),
        "space_app.py": HF_SPACE_APP,
        "README.md": HF_SPACE_README.format(gradio_version=gradio_version),
        "NOTES.md": NOTES.format(port=port),
    }
    written: list[str] = []
    for name, content in files.items():
        path = target / name
        path.write_text(content, encoding="utf-8")
        written.append(str(path))
    return written


def summary(port: int, target: Path | str) -> dict[str, Any]:
    return {
        "target": str(target),
        "docker": f"docker compose -f {Path(target) / 'docker-compose.yml'} up -d --build",
        "systemd": f"sudo cp {Path(target) / 'archivist.service'} /etc/systemd/system/ && sudo systemctl enable --now archivist",
        "windows": f"schtasks /Create /TN ARCHIVIST /XML {Path(target) / 'windows-task.xml'}",
        "url": f"http://localhost:{port}",
    }
